{ config, pkgs, ... }:

let
  hmSwitchCmd = "nix run .#home-manager -- switch --flake .";
  hmRollbackCmd = "nix run .#home-manager -- switch --rollback --flake .";
  grepBin = "${pkgs.gnugrep}/bin/grep";
  awkBin = "${pkgs.gawk}/bin/awk";
  refreshManagedAppSourcesCmd = ''
        if command -v curl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
          qq_payload="$(curl -fsSL https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxConfig.js | ${grepBin} -oP 'var params= \K\{.*\}(?=;)' || true)"
          if [ -n "$qq_payload" ]; then
            qq_version="$(printf '%s' "$qq_payload" | jq -r '.version')-$(printf '%s' "$qq_payload" | jq -r '.updateDate')"
            qq_url="$(printf '%s' "$qq_payload" | jq -r '.x64DownloadUrl.deb')"
            qq_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$qq_url")")"
            cat > qq-sources.nix <<EOF
    # Generated by hms source refresh. Do not edit manually.
    # Last updated: $(date +%F)
    { fetchurl }:
    {
      x86_64-linux = {
        version = "$qq_version";
        src = fetchurl {
          url = "$qq_url";
          hash = "$qq_hash";
        };
      };
    }
    EOF
            echo "[hms] qq sources refreshed to $qq_version"
          fi

          karing_payload="$(curl -fsSL https://api.github.com/repos/KaringX/karing/releases/latest || true)"
          if [ -n "$karing_payload" ]; then
            karing_tag="$(printf '%s' "$karing_payload" | jq -r '.tag_name')"
            karing_version="''${karing_tag#v}"
            karing_url="$(printf '%s' "$karing_payload" | jq -r '.assets[].browser_download_url' | ${grepBin} 'linux_amd64\.rpm$' | head -n1)"
            if [ -n "$karing_url" ]; then
              karing_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$karing_url")")"
              cat > karing-sources.nix <<EOF
    # Generated by hms source refresh. Do not edit manually.
    # Last updated: $(date +%F)
    { fetchurl }:
    {
      x86_64-linux = {
        version = "$karing_version";
        src = fetchurl {
          url = "$karing_url";
          hash = "$karing_hash";
        };
      };
    }
    EOF
              echo "[hms] karing sources refreshed to $karing_version"
            fi
          fi
        fi
  '';
  updateNvidiaMetadataCmd = ''
    if [ -r /proc/driver/nvidia/version ]; then
      current_version="$(${awkBin} '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' /proc/driver/nvidia/version)"
      stored_version=""
      if [ -f nvidia/version ]; then
        stored_version="$(${awkBin} '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' nvidia/version)"
      fi

      version_updated=0
      if [ ! -f nvidia/version ] || ! cmp -s /proc/driver/nvidia/version nvidia/version; then
        cat /proc/driver/nvidia/version > nvidia/version
        version_updated=1
        echo "[hms] nvidia/version updated"
      fi

      if [ "$version_updated" -eq 1 ] || [ ! -s nvidia/hash ] || ! ${grepBin} -Eq '^sha256-[A-Za-z0-9+/=]+$' nvidia/hash; then
        if [ -z "$current_version" ]; then
          echo "[hms] unable to parse NVIDIA version for hash update" >&2
          exit 1
        fi
        nvidia_url="https://download.nvidia.com/XFree86/Linux-x86_64/$current_version/NVIDIA-Linux-x86_64-$current_version.run"
        nvidia_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$nvidia_url")")"
        printf '%s\n' "$nvidia_hash" > nvidia/hash
        if [ "$current_version" != "$stored_version" ]; then
          echo "[hms] nvidia/hash updated for $current_version"
        else
          echo "[hms] nvidia/hash refreshed"
        fi
      fi
    fi
  '';
in
{
  home.file = config.local.nixgl.binScripts // {
    ".zsh_aliases".text =
      let
        escapeAliasValue = v: builtins.replaceStrings [ "'" ] [ "'\\''" ] v;
        allAliases = config.local.nixgl.shellAliases // {
          hms = "cd ~/.config/home-manager && { ${refreshManagedAppSourcesCmd}; ${updateNvidiaMetadataCmd}; ${hmSwitchCmd}; }";
          hmu = "cd ~/.config/home-manager && { ${refreshManagedAppSourcesCmd}; ${updateNvidiaMetadataCmd}; nix flake update && ${hmSwitchCmd}; }";
          hmr = "cd ~/.config/home-manager && ${hmRollbackCmd}";
        };
      in
      pkgs.lib.concatStringsSep "\n" (
        pkgs.lib.mapAttrsToList (k: v: "alias ${k}='${escapeAliasValue v}'") allAliases
      );

    ".config/home-manager/zsh-extra.sh".text = ''
      if [ -n "$ZSH_VERSION" ]; then
        path=(/usr/local/bin /usr/bin /usr/local/sbin /usr/sbin ''${HOME}/.cache/.bun/bin ''${path})
        path=(''${path:#''${HOME}/.nix-profile/bin} ''${path:#/nix/var/nix/profiles/default/bin})
        path+=("''${HOME}/.nix-profile/bin" /nix/var/nix/profiles/default/bin)
        typeset -U path
        export PATH
      fi
    '';
  };
}
