#!/usr/bin/env bash
set -euo pipefail

grep_bin="@grep_bin@"
awk_bin="@awk_bin@"
sha256sum_bin="@sha256sum_bin@"
runtime_shell="@runtime_shell@"

# sources/*.nix are generated metadata only. Package construction stays in flake.nix
# and karing.nix; this script is the only place that mutates those files.

refresh_managed_app_sources() {
  if ! command -v curl >/dev/null 2>&1; then
    return 0
  fi

  local has_jq=0
  if command -v jq >/dev/null 2>&1; then
    has_jq=1
  fi

  local existing_qq_version=""
  local existing_qq_url=""
  local existing_qq_hash=""
  if [ -f sources/qq.nix ]; then
    existing_qq_version="$($grep_bin -oP 'version = "\K[^"]+' sources/qq.nix | head -n1 || true)"
    existing_qq_url="$($grep_bin -oP 'url = "\K[^"]+' sources/qq.nix | head -n1 || true)"
    existing_qq_hash="$($grep_bin -oP 'hash = "\K[^"]+' sources/qq.nix | head -n1 || true)"
  fi

  local existing_karing_version=""
  local existing_karing_url=""
  local existing_karing_hash=""
  if [ -f sources/karing.nix ]; then
    existing_karing_version="$($grep_bin -oP 'version = "\K[^"]+' sources/karing.nix | head -n1 || true)"
    existing_karing_url="$($grep_bin -oP 'url = "\K[^"]+' sources/karing.nix | head -n1 || true)"
    existing_karing_hash="$($grep_bin -oP 'hash = "\K[^"]+' sources/karing.nix | head -n1 || true)"
  fi

  if [ "$has_jq" -eq 1 ]; then
    local qq_config_payload=""
    qq_config_payload="$(curl -fsSL https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxConfig.js | "$grep_bin" -oP 'var params= \K\{.*\}(?=;)' || true)"
    local qq_log_payload=""
    qq_log_payload="$(curl -fsSL https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxLog.js || true)"
    local qq_log_version=""
    local qq_log_date=""
    if [ -n "$qq_log_payload" ]; then
      qq_log_version="$(printf '%s' "$qq_log_payload" | "$grep_bin" -oP 'QQ Linux版 \K[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true)"
      qq_log_date="$(printf '%s' "$qq_log_payload" | "$grep_bin" -oP 'date":"\K[^"]+' | head -n1 || true)"
    fi

    if [ -n "$qq_config_payload" ]; then
      local qq_config_version=""
      local qq_config_date=""
      local qq_config_url=""
      qq_config_version="$(printf '%s' "$qq_config_payload" | jq -r '.version')"
      qq_config_date="$(printf '%s' "$qq_config_payload" | jq -r '.updateDate')"
      qq_config_url="$(printf '%s' "$qq_config_payload" | jq -r '.x64DownloadUrl.deb')"

      local qq_source_type="fetchurl"
      local qq_source_url="$qq_config_url"
      local qq_source_hash=""
      local qq_source_path=""
      local qq_effective_version="$qq_config_version-$qq_config_date"

      if [ -n "$qq_log_version" ] && [ "$qq_log_version" != "$qq_config_version" ]; then
        local candidate_local=""
        candidate_local="$(find "$HOME/Downloads" -maxdepth 1 -type f -name "*${qq_log_version}*amd64*.deb" | sort | tail -n1 || true)"
        if [ -n "$candidate_local" ]; then
          qq_source_type="path"
          qq_source_path="$candidate_local"
          qq_effective_version="$qq_log_version-$qq_log_date"
          echo "[hms] qq using local package for newer update-channel version $qq_log_version"
        else
          echo "[hms] qq update channel advertises $qq_log_version but no stable downloadable package was found; keeping public package source $qq_config_version"
        fi
      fi

      if [ "$qq_source_type" = "fetchurl" ]; then
        if [ "$existing_qq_version" = "$qq_effective_version" ] && [ "$existing_qq_url" = "$qq_source_url" ] && [ -n "$existing_qq_hash" ]; then
          qq_source_hash="$existing_qq_hash"
        else
          qq_source_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$qq_source_url")")"
        fi
      fi

      cat > sources/qq.nix <<EOF
# Generated by hms source refresh. Do not edit manually.
# Last updated: $(date +%F)
{ fetchurl }:
{
  x86_64-linux = {
    version = "$qq_effective_version";
    updateChannelVersion = "$qq_log_version";
    updateChannelDate = "$qq_log_date";
    src = {
      type = "$qq_source_type";
EOF
      if [ "$qq_source_type" = "path" ]; then
        cat >> sources/qq.nix <<EOF
      path = "$qq_source_path";
EOF
      else
        cat >> sources/qq.nix <<EOF
      url = "$qq_source_url";
      hash = "$qq_source_hash";
EOF
      fi
      cat >> sources/qq.nix <<EOF
    };
  };
}
EOF
      echo "[hms] qq sources refreshed to $qq_effective_version"
    fi

    local karing_payload=""
    karing_payload="$(curl -fsSL https://api.github.com/repos/KaringX/karing/releases/latest || true)"
    if [ -n "$karing_payload" ]; then
      local karing_tag=""
      karing_tag="$(printf '%s' "$karing_payload" | jq -r '.tag_name')"
      local karing_version="${karing_tag#v}"
      local karing_url=""
      karing_url="$(printf '%s' "$karing_payload" | jq -r '.assets[].browser_download_url' | "$grep_bin" 'linux_amd64\.rpm$' | head -n1)"
      if [ -n "$karing_url" ]; then
        local karing_hash=""
        if [ "$existing_karing_version" = "$karing_version" ] && [ "$existing_karing_url" = "$karing_url" ] && [ -n "$existing_karing_hash" ]; then
          karing_hash="$existing_karing_hash"
        else
          karing_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$karing_url")")"
        fi
        cat > sources/karing.nix <<EOF
# Generated by hms source refresh. Do not edit manually.
# Last updated: $(date +%F)
{ fetchurl }:
{
  x86_64-linux = {
    version = "$karing_version";
    src = fetchurl {
      url = "$karing_url";
      hash = "$karing_hash";
    };
  };
}
EOF
        echo "[hms] karing sources refreshed to $karing_version"
      fi
    fi
  fi
}

update_nvidia_metadata() {
  if [ -r /proc/driver/nvidia/version ]; then
    local current_version=""
    current_version="$($awk_bin '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' /proc/driver/nvidia/version)"
    local stored_version=""
    if [ -f nvidia/version ]; then
      stored_version="$($awk_bin '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' nvidia/version)"
    fi

    local version_updated=0
    if [ ! -f nvidia/version ] || ! cmp -s /proc/driver/nvidia/version nvidia/version; then
      cat /proc/driver/nvidia/version > nvidia/version
      version_updated=1
      echo "[hms] nvidia/version updated"
    fi

    if [ "$version_updated" -eq 1 ] || [ ! -s nvidia/hash ] || ! "$grep_bin" -Eq '^sha256-[A-Za-z0-9+/=]+$' nvidia/hash; then
      if [ -z "$current_version" ]; then
        echo "[hms] unable to parse NVIDIA version for hash update" >&2
        exit 1
      fi
      local nvidia_url="https://download.nvidia.com/XFree86/Linux-x86_64/$current_version/NVIDIA-Linux-x86_64-$current_version.run"
      local nvidia_hash=""
      nvidia_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$nvidia_url")")"
      printf '%s\n' "$nvidia_hash" > nvidia/hash
      if [ "$current_version" != "$stored_version" ]; then
        echo "[hms] nvidia/hash updated for $current_version"
      else
        echo "[hms] nvidia/hash refreshed"
      fi
    fi
  fi
}

sync_karing_system_helper() {
  local karing_helper_src="$HOME/.nix-profile/share/karing/karingService.bin"
  local karing_helper_dst="/usr/local/libexec/karing/karingService-root"
  local polkit_rule_dst="/etc/polkit-1/rules.d/49-karing-tun.rules"
  local desired_user="$USER"

  if [ -f "$karing_helper_src" ] && command -v pkexec >/dev/null 2>&1; then
    cat > /tmp/49-karing-tun.rules <<EOF
polkit.addRule(function(action, subject) {
  if (action.id == "org.freedesktop.policykit.exec" &&
      action.lookup("program") == "/usr/local/libexec/karing/karingService-root" &&
      subject.user == "$desired_user" &&
      subject.local) {
    return polkit.Result.YES;
  }
});
EOF

    local helper_needs_sync=1
    if [ -f "$karing_helper_dst" ] && cmp -s "$karing_helper_src" "$karing_helper_dst"; then
      helper_needs_sync=0
    fi

    local rule_needs_sync=1
    if [ -f "$polkit_rule_dst" ] && cmp -s /tmp/49-karing-tun.rules "$polkit_rule_dst"; then
      rule_needs_sync=0
    fi

    if [ "$helper_needs_sync" -eq 1 ] || [ "$rule_needs_sync" -eq 1 ]; then
      echo "[hms] syncing karing system helper and polkit rule"
      if ! env SHELL=/bin/sh pkexec "$runtime_shell" -c '
        set -eu
        install -d -m 0755 /usr/local/libexec/karing
        install -m 4755 "'$karing_helper_src'" "'$karing_helper_dst'"
        chown root:root "'$karing_helper_dst'"
        install -d -m 0755 /etc/polkit-1/rules.d
        install -m 0644 /tmp/49-karing-tun.rules "'$polkit_rule_dst'"
        chown root:root "'$polkit_rule_dst'"
      '; then
        echo "[hms] warning: karing system helper sync was skipped; run karing once in a graphical session or retry hms if TUN auth changes are needed" >&2
      fi
    fi

    rm -f /tmp/49-karing-tun.rules
  fi
}

refresh_managed_app_sources
update_nvidia_metadata
nix run .#home-manager -- switch --flake .
sync_karing_system_helper
