# Generated by hms source refresh. Do not edit manually.
# Last updated: 2026-04-03
{ fetchurl }:
{
  x86_64-linux = {
    version = "3.2.25-2026-02-05";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.25_260205_amd64_01.deb";
      hash = "sha256-TVEHWd8lyfhcfj6E83XDaFq2L75wtNNI97osG6iCvuA=";
    };
  };
}
