# Generated by hms source refresh. Do not edit manually.
# Last updated: 2026-04-05
{ fetchurl }:
{
  x86_64-linux = {
    version = "6.7.2";
    src = fetchurl {
      url = "https://td.telegram.org/tlinux/tsetup.6.7.2.tar.xz";
      hash = "sha256-iRzxjc9sj3oHPQfvlB7nmpvya3GboJ7saToyFBrcs3w=";
    };
  };
}
