# Generated by hms source refresh. Do not edit manually.
# Last updated: 2026-05-20
{ fetchurl }:
{
  x86_64-linux = {
    version = "1.2.18.2102";
    src = fetchurl {
      url = "https://github.com/KaringX/karing/releases/download/v1.2.18.2102/karing_1.2.18.2102_linux_amd64.rpm";
      hash = "sha256-PKVQdMe/QfetrIqiNJ8xx2Iy0zJsJxkYg5UBimZIsTQ=";
    };
  };
}
