# Generated by hms source refresh. Do not edit manually.
# Last updated: 2026-04-04
# Metadata only: package definitions may consume this file, but mutation stays in hms-refresh.sh.
{ fetchurl }:
{
  x86_64-linux = {
    version = "1.2.15.1806";
    src = fetchurl {
      url = "https://github.com/KaringX/karing/releases/download/v1.2.15.1806/karing_1.2.15.1806_linux_amd64.rpm";
      hash = "sha256-C6QAgJICc96ML9l4+JzC16XpZ8UufQdc8Yrsdc/Qeqc=";
    };
  };
}
