# Generated by hms source refresh. Do not edit manually.
# Last updated: 2026-06-29
{ fetchurl }:
{
  x86_64-linux = {
    version = "1.2.21.2402";
    src = fetchurl {
      url = "https://github.com/KaringX/karing/releases/download/v1.2.21.2402/karing_1.2.21.2402_linux_amd64.rpm";
      hash = "sha256-2o4+twPeWCXDBSH08CdF5NSAYn52jXIhkFTtIkxEpdU=";
    };
  };
}
