#!/usr/bin/env bash
set -euo pipefail

grep_bin="@grep_bin@"
awk_bin="@awk_bin@"
sha256sum_bin="@sha256sum_bin@"
runtime_shell="@runtime_shell@"

# sources/*.nix are generated metadata only. This script is the only place that
# mutates locally-managed vendor source files.

refresh_managed_app_sources() {
  if ! command -v curl >/dev/null 2>&1; then
    return 0
  fi

  local has_jq=0
  if command -v jq >/dev/null 2>&1; then
    has_jq=1
  fi

  local existing_karing_version=""
  local existing_karing_url=""
  local existing_karing_hash=""
  if [ -f sources/karing.nix ]; then
    existing_karing_version="$($grep_bin -oP 'version = "\K[^"]+' sources/karing.nix | head -n1 || true)"
    existing_karing_url="$($grep_bin -oP 'url = "\K[^"]+' sources/karing.nix | head -n1 || true)"
    existing_karing_hash="$($grep_bin -oP 'hash = "\K[^"]+' sources/karing.nix | head -n1 || true)"
  fi

  if [ "$has_jq" -eq 1 ]; then
    local karing_payload=""
    karing_payload="$(curl -fsSL https://api.github.com/repos/KaringX/karing/releases/latest || true)"
    if [ -n "$karing_payload" ]; then
      local karing_tag=""
      karing_tag="$(printf '%s' "$karing_payload" | jq -r '.tag_name')"
      local karing_version="${karing_tag#v}"
      local karing_url=""
      karing_url="$(printf '%s' "$karing_payload" | jq -r '.assets[].browser_download_url' | "$grep_bin" 'linux_amd64\.rpm$' | head -n1)"
      if [ -n "$karing_url" ]; then
        local karing_hash=""
        if [ "$existing_karing_version" = "$karing_version" ] && [ "$existing_karing_url" = "$karing_url" ] && [ -n "$existing_karing_hash" ]; then
          karing_hash="$existing_karing_hash"
        else
          karing_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$karing_url")")"
        fi
        cat > sources/karing.nix <<EOF
# Generated by hms source refresh. Do not edit manually.
# Last updated: $(date +%F)
{ fetchurl }:
{
  x86_64-linux = {
    version = "$karing_version";
    src = fetchurl {
      url = "$karing_url";
      hash = "$karing_hash";
    };
  };
}
EOF
        echo "[hms] karing sources refreshed to $karing_version"
      fi
    fi
  fi
}

update_nvidia_metadata() {
  if [ -r /proc/driver/nvidia/version ]; then
    local current_version=""
    current_version="$($awk_bin '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' /proc/driver/nvidia/version)"
    local stored_version=""
    if [ -f nvidia/version ]; then
      stored_version="$($awk_bin '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' nvidia/version)"
    fi

    local version_updated=0
    if [ ! -f nvidia/version ] || ! cmp -s /proc/driver/nvidia/version nvidia/version; then
      cat /proc/driver/nvidia/version > nvidia/version
      version_updated=1
      echo "[hms] nvidia/version updated"
    fi

    if [ "$version_updated" -eq 1 ] || [ ! -s nvidia/hash ] || ! "$grep_bin" -Eq '^sha256-[A-Za-z0-9+/=]+$' nvidia/hash; then
      if [ -z "$current_version" ]; then
        echo "[hms] unable to parse NVIDIA version for hash update" >&2
        exit 1
      fi
      local nvidia_url="https://download.nvidia.com/XFree86/Linux-x86_64/$current_version/NVIDIA-Linux-x86_64-$current_version.run"
      local nvidia_hash=""
      nvidia_hash="$(nix hash to-sri --type sha256 "$(nix-prefetch-url "$nvidia_url")")"
      printf '%s\n' "$nvidia_hash" > nvidia/hash
      if [ "$current_version" != "$stored_version" ]; then
        echo "[hms] nvidia/hash updated for $current_version"
      else
        echo "[hms] nvidia/hash refreshed"
      fi
    fi
  fi
}

refresh_managed_app_sources
update_nvidia_metadata
nix run .#home-manager -- switch --flake .
