#!/usr/bin/env bash
set -euo pipefail

grep_bin="@grep_bin@"
awk_bin="@awk_bin@"
curl_bin="@curl_bin@"
jq_bin="@jq_bin@"
nix_bin="@nix_bin@"
nix_instantiate_bin="@nix_instantiate_bin@"
nix_prefetch_url_bin="@nix_prefetch_url_bin@"

# sources/*.nix are generated metadata only. This script is the only place that
# mutates locally-managed vendor source files.

refresh_managed_app_sources() {
  if [ ! -x "$curl_bin" ] || [ ! -x "$jq_bin" ]; then
    echo "[hms] required source refresh tools are unavailable" >&2
    exit 1
  fi

  local existing_karing_version=""
  local existing_karing_url=""
  local existing_karing_hash=""
  if [ -f sources/karing.nix ]; then
    existing_karing_version="$($grep_bin -oP 'version = "\K[^"]+' sources/karing.nix | head -n1 || true)"
    existing_karing_url="$($grep_bin -oP 'url = "\K[^"]+' sources/karing.nix | head -n1 || true)"
    existing_karing_hash="$($grep_bin -oP 'hash = "\K[^"]+' sources/karing.nix | head -n1 || true)"
  fi

  local karing_payload=""
  karing_payload="$("$curl_bin" -fsSL https://api.github.com/repos/KaringX/karing/releases/latest || true)"
  if [ -n "$karing_payload" ]; then
    local karing_tag=""
    karing_tag="$(printf '%s' "$karing_payload" | "$jq_bin" -r '.tag_name // empty')"
    local karing_version="${karing_tag#v}"
    local karing_url=""
    set +e
    karing_url="$(printf '%s' "$karing_payload" | "$jq_bin" -r '.assets[].browser_download_url // empty' | "$grep_bin" 'linux_amd64\.rpm$' | head -n1)"
    set -e
    if [ -n "$karing_url" ]; then
      if ! printf '%s\n' "$karing_version" | "$grep_bin" -Eq '^[0-9]+(\.[0-9]+)+$'; then
        echo "[hms] invalid Karing release version: ${karing_version:-empty}" >&2
        exit 1
      fi
      if ! printf '%s\n' "$karing_url" | "$grep_bin" -Eq '^https://github\.com/KaringX/karing/releases/download/v[^/]+/karing_[^/]+_linux_amd64\.rpm$'; then
        echo "[hms] invalid Karing release asset URL: $karing_url" >&2
        exit 1
      fi

      local karing_hash=""
      if [ "$existing_karing_version" = "$karing_version" ] && [ "$existing_karing_url" = "$karing_url" ] && [ -n "$existing_karing_hash" ]; then
        karing_hash="$existing_karing_hash"
      else
        karing_hash="$("$nix_bin" hash to-sri --type sha256 "$("$nix_prefetch_url_bin" "$karing_url")")"
      fi
      if ! printf '%s\n' "$karing_hash" | "$grep_bin" -Eq '^sha256-[A-Za-z0-9+/=]+$'; then
        echo "[hms] invalid Karing source hash: ${karing_hash:-empty}" >&2
        exit 1
      fi

      local karing_source_tmp=""
      karing_source_tmp="$(mktemp sources/karing.nix.XXXXXX)"
      cat > "$karing_source_tmp" <<EOF
# Generated by hms source refresh. Do not edit manually.
# Last updated: $(date +%F)
{ fetchurl }:
{
  x86_64-linux = {
    version = "$karing_version";
    src = fetchurl {
      url = "$karing_url";
      hash = "$karing_hash";
    };
  };
}
EOF
      "$nix_instantiate_bin" --parse "$karing_source_tmp" >/dev/null
      mv "$karing_source_tmp" sources/karing.nix
      echo "[hms] karing sources refreshed to $karing_version"
    fi
  fi
}

update_nvidia_metadata() {
  if [ ! -r /proc/driver/nvidia/version ]; then
    return 0
  fi

  local current_version=""
  # shellcheck disable=SC2016
  current_version="$($awk_bin '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' /proc/driver/nvidia/version)"

  # Normalized /proc content (trailing whitespace stripped) for a stable compare.
  local normalized_version=""
  normalized_version="$(mktemp)"
  "$awk_bin" '{ sub(/[[:space:]]+$/, ""); print }' /proc/driver/nvidia/version > "$normalized_version"

  # Which version was the stored hash computed for? Lets a partial write self-heal:
  # if version advanced but the hash did not, hash_version != current_version and
  # we re-fetch instead of wedging the build on a stale-but-format-valid hash.
  local hash_version=""
  if [ -f nvidia/hash-version ]; then
    IFS= read -r hash_version < nvidia/hash-version || true
  fi

  # Decide whether a hash refresh is needed WITHOUT mutating any file yet. This
  # preserves the skip-when-unchanged gate (nix-prefetch-url downloads the ~300MB
  # .run, so we only do it when something actually changed).
  local needs_hash_update=0
  if [ ! -f nvidia/version ] || ! cmp -s "$normalized_version" nvidia/version; then
    needs_hash_update=1 # driver version changed
  elif [ ! -s nvidia/hash ] || ! "$grep_bin" -Eq '^sha256-[A-Za-z0-9+/=]+$' nvidia/hash; then
    needs_hash_update=1 # hash missing or corrupt
  elif [ "$hash_version" != "$current_version" ]; then
    needs_hash_update=1 # stored hash does not correspond to the current version
  fi

  if [ "$needs_hash_update" -eq 0 ]; then
    rm -f "$normalized_version"
    return 0
  fi

  if [ -z "$current_version" ]; then
    rm -f "$normalized_version"
    echo "[hms] unable to parse NVIDIA version for hash update" >&2
    exit 1
  fi

  # Prefetch + validate the hash BEFORE committing nvidia/version. A failed
  # prefetch aborts here (set -e) with all three files still at their old,
  # mutually-consistent values, instead of leaving version ahead of hash.
  local nvidia_url="https://download.nvidia.com/XFree86/Linux-x86_64/$current_version/NVIDIA-Linux-x86_64-$current_version.run"
  local nvidia_hash=""
  nvidia_hash="$("$nix_bin" hash to-sri --type sha256 "$("$nix_prefetch_url_bin" "$nvidia_url")")"
  if ! printf '%s\n' "$nvidia_hash" | "$grep_bin" -Eq '^sha256-[A-Za-z0-9+/=]+$'; then
    rm -f "$normalized_version"
    echo "[hms] invalid NVIDIA source hash for $current_version: ${nvidia_hash:-empty}" >&2
    exit 1
  fi

  # Commit all three together: hash + its version sidecar first, then version.
  printf '%s\n' "$nvidia_hash" > nvidia/hash
  printf '%s\n' "$current_version" > nvidia/hash-version
  mv "$normalized_version" nvidia/version
  echo "[hms] nvidia metadata updated for $current_version"
}

export NIX_SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

refresh_managed_app_sources
update_nvidia_metadata
"$nix_bin" run .#home-manager -- switch --flake .
